//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_service = new HashSet<order_service>();
        }
    
        public int id_order { get; set; }
        public string code_order { get; set; }
        public Nullable<System.DateTime> date_order_open { get; set; }
        public string time_order { get; set; }
        public int code_client { get; set; }
        public int status_id { get; set; }
        public Nullable<System.DateTime> date_order_close { get; set; }
        public string time_rent { get; set; }
    
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_service> order_service { get; set; }
        public virtual status status { get; set; }
    }
}
