//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id_user { get; set; }
        public string fio { get; set; }
        public int role_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> date_exit { get; set; }
    
        public virtual role role { get; set; }
    }
}
